language: scala

scala:
  - 2.10.5

jdk:
  - oraclejdk7
  - openjdk7

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test &&
        sbt coverageAggregate

after_success: sbt coveralls

env:
  global:
    - secure: "HgNbdZ47VG7Plfqd5GvUrOE8QP639vMWpSqx/XvNu/92OXXyKCxq3HvKo5UkYIBLhGKOK+B+xFdsJXV9GgMXOnqGwPhym3VMfK3Md+3IXtZPESD32PwZTmDtgn3OZCpYeASSkOJ2sN2uT+NpRx8Wr8/2LhguY9BT1JgkWV0xytDtTVSwVoCZo6oMdAZhO6xS2MUo93JBaxlzobQ1mNLJVyE0/hZ5jWj3SM+xwdGw9x0MZCaiDa6/0LM9ESmq7v6fFNnTUwKiFRYuSqOc1KdCXdesbUN7H94EoSBNC1aqqwuqFYfA6fkJZPvLLPCp66NgUF37tBecxnCYDDEU5Az+Rk/TYNu69QNqZ4u1EJvom1Dibf3d/4lHN271gW/ZO+/EbJTUB2c6YfZ7bZS+IrxF3wf0Hf3mjO7RXez1pM1bM2YxMjB7mo1cJpb5D5PMZU2/tohf1FjC1KJgNlcaYLiqjNjYM13FQhcGObkwBsUGOlNZ8FMqZJwvdFKupcre37Rjm6fSneL9BfOig0D9MSB8obM0riDWjYXyxYWZisclYZ3OjShb9mNosVNtCza8/FZWbPulU1+BNwIwX/Z8xxcDsGITeu3W5wo/3zs7FNu6zxe5UxEtI+5JOVMfYNqWlY5bQH5u7ScNKmDJQgriaeWPMLFp6eBOyCvKvXM5EenZQww="